remote_theme: mmistakes/minimal-mistakes@4.25.1

plugins:
  - jekyll-remote-theme

title: My Dev Blog
description: Game Design Course Blog

# 开启 collections（关键！）
collections:
  weeks:
    output: true
